ALTER TABLE "projects" DROP COLUMN "sections",
ADD COLUMN     "content" TEXT,
ALTER COLUMN "blurb" DROP NOT NULL,
ALTER COLUMN "summary" DROP NOT NULL,
ALTER COLUMN "year" DROP NOT NULL,
ALTER COLUMN "kind" DROP NOT NULL,
ALTER COLUMN "metrics" SET DEFAULT '[]';

